[2023-09-04 20:28:02,414] ERROR log_exception() L1449 Exception on /modelo [POST] - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py", line 251, in add_modelo
    modelo = Modelo(
             ^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'cod_modelo'
[2023-09-04 20:28:02,422] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:28:02] "[35m[1mPOST /modelo HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:12,913] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:17,421] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:30:17] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:17,514] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:30:17] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:17,519] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:30:17] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:17,520] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:30:17] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:17,658] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:30:17] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:17,664] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:30:17] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:30:23,138] ERROR log_exception() L1449 Exception on /modelo [POST] - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py", line 251, in add_modelo
    modelo = Modelo(
             ^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'cod_modelo'
[2023-09-04 20:30:23,142] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:30:23] "[35m[1mPOST /modelo HTTP/1.1[0m" 500 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:22,759] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:26,060] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:31:26] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:26,162] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:31:26] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:26,167] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:31:26] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:26,168] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:31:26] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:26,260] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:31:26] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:26,266] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:31:26] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:31:32,591] ERROR log_exception() L1449 Exception on /modelo [POST] - call_trace=C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\vm\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py", line 252, in add_modelo
    cod_modelo = form.codigo,
                 ^^^^^^^^^^^
AttributeError: 'ModeloSchema' object has no attribute 'codigo'
