[2023-09-04 19:58:19,247] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 19:58:19] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 19:58:19,251] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 19:58:19] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 19:58:19,251] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 19:58:19] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 19:58:19,387] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 19:58:19] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 19:58:24,468] ERROR log_exception() L1449 Exception on /marca [POST] - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C\app.py", line 53, in add_marca
    marca = Marca(
      ^^^^^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'des_nome'
[2023-09-04 19:58:24,473] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 19:58:24] "[35m[1mPOST /marca HTTP/1.1[0m" 500 - - call_trace=C:\PUC-RIO\Sprint-1\BackEnd\puc-rio-mvp-sprint-1-back-end\venv\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:23,964] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.15.138:5000 (Press CTRL+C to quit) - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:29,391] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:29] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:29,413] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:29] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:29,490] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:29] "GET /openapi/static/images/swagger.svg HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:29,522] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:29] "GET /openapi/static/images/redoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:29,526] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:29] "GET /openapi/static/images/rapidoc.svg HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:31,362] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:31] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:31,376] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:31] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:31,396] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:31] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:31,417] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:31] "[36mGET /openapi/static/images/redoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:31,421] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:31] "[36mGET /openapi/static/images/rapidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:34,169] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:34] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:34,192] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:34] "GET /openapi/static/css/swagger-ui.css HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:34,216] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:34] "GET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:34,218] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:34] "GET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:34,359] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:34] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
[2023-09-04 20:10:39,731] ERROR log_exception() L1449 Exception on /marca [POST] - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\mvp\puc-rio-mvp-sprint-3-component-C-2\app.py", line 53, in add_marca
    marca = Marca(
      ^^^^^^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'des_nome'
[2023-09-04 20:10:39,737] INFO _log() L224  127.0.0.1 - - [04/Sep/2023 20:10:39] "[35m[1mPOST /marca HTTP/1.1[0m" 500 - - call_trace=C:\Users\edumi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L224 
